name: Build articles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Download claat
      run: go install github.com/googlecodelabs/tools/claat@v1.0.4

    - name: Build markdown files
      run: |
        cd site/codelabs
        claat export ./*.md

